version: "3"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/deal41
    environment:
      NODE_ENV: ${NODE_ENV}
    # depends_on:
