version: "3"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/deal41
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deal41 # Created at first launch
      POSTGRES_PASSWORD: a_really_secure_password
